# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AI Hackathon 2019' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AI Hackathon 2019
  pod 'SPPermission'
  pod "Hero"
  pod 'MKRingProgressView'
  

  target 'AI Hackathon 2019Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
